name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout!
      uses: actions/checkout@v1
    - name: Setup .NET Environment.
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102'
    - name: Build and run tests.
      run: dotnet test --filter os~nix --collect:"XPlat Code Coverage"
    - name: Make artifacts directory.
      run: mkdir -p artifacts
    - name: Copy artifacts.
      run: |
        find . -type f -name Sheller.dll -exec cp '{}' ./artifacts/. ';'
        find . -type f -name Sheller.pdb -exec cp '{}' ./artifacts/. ';'
        find . -type f -name Sheller.xml -exec cp '{}' ./artifacts/. ';'
        find . -type f -name coverage.cobertura.xml -exec cp '{}' ./artifacts/. ';'
    - name: Upload artifacts.
      uses: actions/upload-artifact@master
      with:
        name: artifacts
        path: artifacts
    - name: Upload code coverage to codecov.io.
      run: |
        curl -s https://codecov.io/bash > codecov
        chmod +x codecov
        ./codecov -f ./artifacts/coverage.cobertura.xml -t ${{ secrets.CODECOV_KEY }}
    
